import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';
import 'dotenv/config';

async function main() {
  console.log('Seeding database...');
  
  const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
  });
  const adapter = new PrismaPg(pool);
  const prisma = new PrismaClient({ adapter });

  try {
    // 1. Upsert default settings
    const settings = await prisma.setting.upsert({
      where: { id: 'default' },
      update: {},
      create: {
        id: 'default',
        googleMapsApiKey: process.env.GOOGLE_MAPS_API_KEY || '',
        maxZipsPerCampaign: 10,
        maxQueriesPerZip: 5,
        maxWebsitesScannedPerMinute: 10,
        websiteTimeoutSeconds: 15,
        enableJsScanDefault: false,
        defaultExportFormat: 'sales',
        excludedDomains: 'facebook.com,yelp.com,youtube.com,instagram.com,twitter.com,linkedin.com,pinterest.com,yellowpages.com,mapquest.com,tripadvisor.com',
        excludedBusinessNames: 'AutoZone,O\'Reilly,Advance Auto,Pep Boys,NAPA Auto Parts,CarMax',
        excludedBusinessStatuses: 'CLOSED_PERMANENTLY',
      },
    });
    console.log('Default settings upserted.');

    // Clear previous seed data if needed (cascade delete handles children)
    await prisma.campaign.deleteMany({
      where: {
        name: {
          in: [
            'Georgia Independent Repair Shops',
            'Texas Dealerships',
            'Florida Collision Centers',
          ],
        },
      },
    });

    // 2. Create Completed Campaign
    const campaign1 = await prisma.campaign.create({
      data: {
        name: 'Georgia Independent Repair Shops',
        state: 'Georgia',
        businessCategory: 'Auto Repair',
        searchQueries: 'auto repair shop, mechanic, car repair',
        status: 'complete',
        totalZips: 24,
        processedZips: 24,
        totalPlaceIds: 152,
        uniquePlaceIds: 98,
        totalEnriched: 98,
        totalScanned: 98,
        totalQualified: 65,
        completedAt: new Date(),
      },
    });

    // 3. Create Processing Campaign
    const campaign2 = await prisma.campaign.create({
      data: {
        name: 'Texas Dealerships',
        state: 'Texas',
        businessCategory: 'Dealership',
        searchQueries: 'car dealership, dealership service center',
        status: 'scanning_websites',
        totalZips: 40,
        processedZips: 15,
        totalPlaceIds: 85,
        uniquePlaceIds: 52,
        totalEnriched: 30,
        totalScanned: 12,
        totalQualified: 8,
      },
    });

    // 4. Create Draft Campaign
    const campaign3 = await prisma.campaign.create({
      data: {
        name: 'Florida Collision Centers',
        state: 'Florida',
        businessCategory: 'Body Shop',
        searchQueries: 'auto body shop, collision repair',
        status: 'draft',
        totalZips: 12,
        processedZips: 0,
        totalPlaceIds: 0,
        uniquePlaceIds: 0,
        totalEnriched: 0,
        totalScanned: 0,
        totalQualified: 0,
      },
    });

    console.log('Campaigns created.');

    // 5. Create Mock Leads for Campaign 1 (Georgia)
    const leadsData = [
      {
        businessName: 'Peach Auto Care',
        phoneRaw: '+14045550198',
        phoneFormatted: '(404) 555-0198',
        website: 'https://www.peachautocare.com',
        address: '123 Peachtree St NE, Atlanta, GA 30303',
        city: 'Atlanta',
        state: 'GA',
        zip: '30303',
        latitude: 33.7573,
        longitude: -84.3891,
        googleMapsUrl: 'https://maps.google.com/?cid=111111111',
        businessStatus: 'OPERATIONAL',
        rating: 4.8,
        reviewCount: 612,
        primaryType: 'auto_repair',
        types: 'auto_repair,car_repair,mechanic',
        hoursJson: '{"open_now":false,"periods":[{"close":{"day":1,"time":"1700"},"open":{"day":1,"time":"0800"}},{"close":{"day":2,"time":"1700"},"open":{"day":2,"time":"0800"}},{"close":{"day":3,"time":"1700"},"open":{"day":3,"time":"0800"}},{"close":{"day":4,"time":"1700"},"open":{"day":4,"time":"0800"}},{"close":{"day":5,"time":"1700"},"open":{"day":5,"time":"0800"}}],"weekday_text":["Monday: 8:00 AM – 5:00 PM","Tuesday: 8:00 AM – 5:00 PM","Wednesday: 8:00 AM – 5:00 PM","Thursday: 8:00 AM – 5:00 PM","Friday: 8:00 AM – 5:00 PM","Saturday: Closed","Sunday: Closed"]}',
        hoursSummary: 'Mon-Fri 8:00 AM - 5:00 PM, Sat-Sun Closed',
        mondayOpen: '0800',
        mondayClose: '1700',
        tuesdayOpen: '0800',
        tuesdayClose: '1700',
        wednesdayOpen: '0800',
        wednesdayClose: '1700',
        thursdayOpen: '0800',
        thursdayClose: '1700',
        fridayOpen: '0800',
        fridayClose: '1700',
        saturdayOpen: null,
        saturdayClose: null,
        sundayOpen: null,
        sundayClose: null,
        weekdayCloseTime: '17:00',
        closedSaturday: true,
        closedSunday: true,
        closesBefore6: true,
        afterHoursGap: true,
        score: {
          torqiFitScore: 88,
          leadGrade: 'A',
          dataConfidenceScore: 90,
          primaryBucket: 'Busy Desk / High-Volume Shop',
          secondaryBuckets: 'After-Hours Revenue Leak, Pre-Integrated Software Fit',
          salesHook: 'You have the kind of review volume (612 reviews) that usually means the front desk is busy, especially during peaks. Furthermore, you close at 5:00 PM and are closed weekends, representing a large after-hours gap. TorQi can handle routine calls, collect customer details, and capture leads even when your office is closed or overwhelmed.',
          openingLine: 'Hi, I noticed Peach Auto Care has over 600 reviews with a 4.8 rating, which is fantastic! I was calling because with that volume, your service advisors are probably slammed during peak hours, and since you close at 5 PM, we want to help you capture callers when you\'re closed.',
          outreachPriority: 'High',
          scoreBreakdownJson: '{"closes_before_6":15,"closed_saturday":10,"closed_sunday":10,"reviews_300_plus":15,"rating_4_5_plus":10,"no_text_found":10,"software_detected":15,"phone_available":5,"website_available":5,"business_operational":5,"total":100}',
        },
        scan: {
          scanStatus: 'scanned',
          httpStatus: 200,
          finalUrl: 'https://www.peachautocare.com/',
          homepageTitle: 'Peach Auto Care - Professional Auto Repair Atlanta',
          pagesScanned: 4,
          appointmentPageFound: true,
          appointmentUrl: 'https://www.peachautocare.com/schedule',
          contactPageFound: true,
          contactUrl: 'https://www.peachautocare.com/contact',
          bookingFlowStrength: 'Strong booking flow',
          textCapability: 'Not Found',
          textEvidence: 'No text messaging widgets or instructions found on pages.',
          chatWidgetFound: false,
          formFound: true,
          formType: 'appointment_form',
          detectedSoftware: 'Tekmetric',
          softwareConfidence: 'High',
          softwareEvidence: 'Found widget.tekmetric.com embedded in scheduling iframe.',
          evidenceUrl: 'https://www.peachautocare.com/schedule',
          rawSignalsJson: '{"tekmetric":true,"widget.tekmetric.com":true}',
        }
      },
      {
        businessName: 'Midtown Auto Repair',
        phoneRaw: '+14045550240',
        phoneFormatted: '(404) 555-0240',
        website: 'https://www.midtownautorepair.com',
        address: '789 Ponce de Leon Ave NE, Atlanta, GA 30306',
        city: 'Atlanta',
        state: 'GA',
        zip: '30306',
        latitude: 33.7735,
        longitude: -84.3592,
        googleMapsUrl: 'https://maps.google.com/?cid=222222222',
        businessStatus: 'OPERATIONAL',
        rating: 4.6,
        reviewCount: 219,
        primaryType: 'auto_repair',
        types: 'auto_repair,car_repair,mechanic',
        hoursJson: '{"open_now":false,"periods":[{"close":{"day":1,"time":"1730"},"open":{"day":1,"time":"0800"}},{"close":{"day":2,"time":"1730"},"open":{"day":2,"time":"0800"}},{"close":{"day":3,"time":"1730"},"open":{"day":3,"time":"0800"}},{"close":{"day":4,"time":"1730"},"open":{"day":4,"time":"0800"}},{"close":{"day":5,"time":"1730"},"open":{"day":5,"time":"0800"}}],"weekday_text":["Monday: 8:00 AM – 5:30 PM","Tuesday: 8:00 AM – 5:30 PM","Wednesday: 8:00 AM – 5:30 PM","Thursday: 8:00 AM – 5:30 PM","Friday: 8:00 AM – 5:30 PM","Saturday: Closed","Sunday: Closed"]}',
        hoursSummary: 'Mon-Fri 8:00 AM - 5:30 PM, Sat-Sun Closed',
        mondayOpen: '0800',
        mondayClose: '1730',
        tuesdayOpen: '0800',
        tuesdayClose: '1730',
        wednesdayOpen: '0800',
        wednesdayClose: '1730',
        thursdayOpen: '0800',
        thursdayClose: '1730',
        fridayOpen: '0800',
        fridayClose: '1730',
        saturdayOpen: null,
        saturdayClose: null,
        sundayOpen: null,
        sundayClose: null,
        weekdayCloseTime: '17:30',
        closedSaturday: true,
        closedSunday: true,
        closesBefore6: true,
        afterHoursGap: true,
        score: {
          torqiFitScore: 72,
          leadGrade: 'B',
          dataConfidenceScore: 80,
          primaryBucket: 'After-Hours Revenue Leak',
          secondaryBuckets: 'No Text / Weak Digital Intake',
          salesHook: 'Your shop closes at 5:30 PM and is closed on weekends, but customers encounter vehicle emergencies at all hours. With TorQi, you can capture those late-night tow-ins and scheduling inquiries instead of losing them to shops that are open longer.',
          openingLine: 'Hi, I saw Midtown Auto Repair closes at 5:30 PM and is closed on Saturdays and Sundays. Many vehicle problems arise after-hours; we help shops like yours capture and pre-qualify customers when your team is away.',
          outreachPriority: 'Medium',
          scoreBreakdownJson: '{"closes_before_6":15,"closed_saturday":10,"closed_sunday":10,"rating_4_5_plus":10,"no_text_found":10,"phone_available":5,"website_available":5,"business_operational":5,"total":70}',
        },
        scan: {
          scanStatus: 'scanned',
          httpStatus: 200,
          finalUrl: 'https://www.midtownautorepair.com/',
          homepageTitle: 'Midtown Auto Repair Atlanta',
          pagesScanned: 2,
          appointmentPageFound: false,
          appointmentUrl: null,
          contactPageFound: true,
          contactUrl: 'https://www.midtownautorepair.com/contact',
          bookingFlowStrength: 'Phone-first only',
          textCapability: 'Not Found',
          textEvidence: 'No text options found. Form only has basic fields.',
          chatWidgetFound: false,
          formFound: true,
          formType: 'contact_form',
          detectedSoftware: null,
          softwareConfidence: null,
          softwareEvidence: null,
          evidenceUrl: null,
          rawSignalsJson: '{}',
        }
      },
      {
        businessName: 'Elite Motors Service',
        phoneRaw: '+14045550311',
        phoneFormatted: '(404) 555-0311',
        website: 'https://www.elitemotorsatl.com',
        address: '456 Piedmont Ave NE, Atlanta, GA 30308',
        city: 'Atlanta',
        state: 'GA',
        zip: '30308',
        latitude: 33.7681,
        longitude: -84.3815,
        googleMapsUrl: 'https://maps.google.com/?cid=333333333',
        businessStatus: 'OPERATIONAL',
        rating: 4.9,
        reviewCount: 403,
        primaryType: 'auto_repair',
        types: 'auto_repair,car_repair,mechanic',
        hoursJson: '{"open_now":false,"periods":[{"close":{"day":1,"time":"1800"},"open":{"day":1,"time":"0800"}},{"close":{"day":2,"time":"1800"},"open":{"day":2,"time":"0800"}},{"close":{"day":3,"time":"1800"},"open":{"day":3,"time":"0800"}},{"close":{"day":4,"time":"1800"},"open":{"day":4,"time":"0800"}},{"close":{"day":5,"time":"1800"},"open":{"day":5,"time":"0800"}}],"weekday_text":["Monday: 8:00 AM – 6:00 PM","Tuesday: 8:00 AM – 6:00 PM","Wednesday: 8:00 AM – 6:00 PM","Thursday: 8:00 AM – 6:00 PM","Friday: 8:00 AM – 6:00 PM","Saturday: Closed","Sunday: Closed"]}',
        hoursSummary: 'Mon-Fri 8:00 AM - 6:00 PM, Sat-Sun Closed',
        mondayOpen: '0800',
        mondayClose: '1800',
        tuesdayOpen: '0800',
        tuesdayClose: '1800',
        wednesdayOpen: '0800',
        wednesdayClose: '1800',
        thursdayOpen: '0800',
        thursdayClose: '1800',
        fridayOpen: '0800',
        fridayClose: '1800',
        saturdayOpen: null,
        saturdayClose: null,
        sundayOpen: null,
        sundayClose: null,
        weekdayCloseTime: '18:00',
        closedSaturday: true,
        closedSunday: true,
        closesBefore6: true,
        afterHoursGap: true,
        score: {
          torqiFitScore: 82,
          leadGrade: 'A',
          dataConfidenceScore: 90,
          primaryBucket: 'Pre-Integrated Software Fit',
          secondaryBuckets: 'After-Hours Revenue Leak, Busy Desk / High-Volume Shop',
          salesHook: 'We noticed your website appears to use Shopmonkey. TorQi can be configured directly around your existing Shopmonkey scheduling flow, logging new appointments and customer details without adding a new tool for your advisors to learn.',
          openingLine: 'Hi, I noticed Elite Motors Service has amazing reviews (4.9 rating!) and appears to be using Shopmonkey. We build voice and text integrations for Shopmonkey users to automate booking and handle overflow calls.',
          outreachPriority: 'High',
          scoreBreakdownJson: '{"closes_before_6":15,"closed_saturday":10,"closed_sunday":10,"reviews_300_plus":15,"rating_4_5_plus":10,"no_text_found":10,"software_detected":15,"phone_available":5,"website_available":5,"business_operational":5,"total":100}',
        },
        scan: {
          scanStatus: 'scanned',
          httpStatus: 200,
          finalUrl: 'https://www.elitemotorsatl.com/',
          homepageTitle: 'Elite Motors - European Auto Repair & Service',
          pagesScanned: 5,
          appointmentPageFound: true,
          appointmentUrl: 'https://www.elitemotorsatl.com/book',
          contactPageFound: true,
          contactUrl: 'https://www.elitemotorsatl.com/contact',
          bookingFlowStrength: 'Strong booking flow',
          textCapability: 'Not Found',
          textEvidence: 'No mobile text capability detected.',
          chatWidgetFound: false,
          formFound: true,
          formType: 'appointment_form',
          detectedSoftware: 'Shopmonkey',
          softwareConfidence: 'High',
          softwareEvidence: 'Found shopmonkey.io script file inside script element tags.',
          evidenceUrl: 'https://www.elitemotorsatl.com/book',
          rawSignalsJson: '{"shopmonkey":true,"shopmonkey.io":true}',
        }
      },
      {
        businessName: 'Quick Oil Change Atlanta',
        phoneRaw: '+14045550422',
        phoneFormatted: '(404) 555-0422',
        website: 'https://www.quickoilchangeatl.com',
        address: '1011 Northside Dr NW, Atlanta, GA 30318',
        city: 'Atlanta',
        state: 'GA',
        zip: '30318',
        latitude: 33.7842,
        longitude: -84.4082,
        googleMapsUrl: 'https://maps.google.com/?cid=444444444',
        businessStatus: 'OPERATIONAL',
        rating: 4.2,
        reviewCount: 45,
        primaryType: 'oil_change',
        types: 'oil_change,auto_repair',
        hoursJson: '{"open_now":false,"periods":[{"close":{"day":1,"time":"1900"},"open":{"day":1,"time":"0800"}},{"close":{"day":2,"time":"1900"},"open":{"day":2,"time":"0800"}},{"close":{"day":3,"time":"1900"},"open":{"day":3,"time":"0800"}},{"close":{"day":4,"time":"1900"},"open":{"day":4,"time":"0800"}},{"close":{"day":5,"time":"1900"},"open":{"day":5,"time":"0800"}},{"close":{"day":6,"time":"1800"},"open":{"day":6,"time":"0800"}}],"weekday_text":["Monday: 8:00 AM – 7:00 PM","Tuesday: 8:00 AM – 7:00 PM","Wednesday: 8:00 AM – 7:00 PM","Thursday: 8:00 AM – 7:00 PM","Friday: 8:00 AM – 7:00 PM","Saturday: 8:00 AM – 6:00 PM","Sunday: Closed"]}',
        hoursSummary: 'Mon-Fri 8:00 AM - 7:00 PM, Sat 8:00 AM - 6:00 PM, Sun Closed',
        mondayOpen: '0800',
        mondayClose: '1900',
        tuesdayOpen: '0800',
        tuesdayClose: '1900',
        wednesdayOpen: '0800',
        wednesdayClose: '1900',
        thursdayOpen: '0800',
        thursdayClose: '1900',
        fridayOpen: '0800',
        fridayClose: '1900',
        saturdayOpen: '0800',
        saturdayClose: '1800',
        sundayOpen: null,
        sundayClose: null,
        weekdayCloseTime: '19:00',
        closedSaturday: false,
        closedSunday: true,
        closesBefore6: false,
        afterHoursGap: true,
        score: {
          torqiFitScore: 48,
          leadGrade: 'C',
          dataConfidenceScore: 75,
          primaryBucket: 'Website Exists, But Conversion Flow Is Weak',
          secondaryBuckets: 'No Text / Weak Digital Intake',
          salesHook: 'Customers find your oil change shop online, but there\'s no direct way to claim a spot or book service. TorQi can place an interactive booking agent on your website, converting visitors into scheduled drop-offs instantly.',
          openingLine: 'Hi, I noticed Quick Oil Change Atlanta has a website but lacks an easy way for customers to schedule an oil change online. We help convert your website traffic into scheduled appointments automatically.',
          outreachPriority: 'Low',
          scoreBreakdownJson: '{"closed_sunday":10,"no_text_found":10,"weak_booking":10,"phone_available":5,"website_available":5,"business_operational":5,"total":45}',
        },
        scan: {
          scanStatus: 'scanned',
          httpStatus: 200,
          finalUrl: 'https://www.quickoilchangeatl.com/',
          homepageTitle: 'Quick Oil Change - Fast Lube Service Atlanta',
          pagesScanned: 3,
          appointmentPageFound: false,
          appointmentUrl: null,
          contactPageFound: true,
          contactUrl: 'https://www.quickoilchangeatl.com/contact',
          bookingFlowStrength: 'Basic contact form',
          textCapability: 'Not Found',
          textEvidence: 'No text messaging capability detected.',
          chatWidgetFound: false,
          formFound: true,
          formType: 'contact_form',
          detectedSoftware: null,
          softwareConfidence: null,
          softwareEvidence: null,
          evidenceUrl: null,
          rawSignalsJson: '{}',
        }
      },
      {
        businessName: 'Apex Auto Electric',
        phoneRaw: '+14045550599',
        phoneFormatted: '(404) 555-0599',
        website: null,
        address: '2020 Cheshire Bridge Rd NE, Atlanta, GA 30324',
        city: 'Atlanta',
        state: 'GA',
        zip: '30324',
        latitude: 33.8123,
        longitude: -84.3541,
        googleMapsUrl: 'https://maps.google.com/?cid=555555555',
        businessStatus: 'OPERATIONAL',
        rating: 4.5,
        reviewCount: 88,
        primaryType: 'auto_repair',
        types: 'auto_repair,car_repair,mechanic',
        hoursJson: '{"open_now":false,"periods":[{"close":{"day":1,"time":"1700"},"open":{"day":1,"time":"0800"}},{"close":{"day":2,"time":"1700"},"open":{"day":2,"time":"0800"}},{"close":{"day":3,"time":"1700"},"open":{"day":3,"time":"0800"}},{"close":{"day":4,"time":"1700"},"open":{"day":4,"time":"0800"}},{"close":{"day":5,"time":"1700"},"open":{"day":5,"time":"0800"}}],"weekday_text":["Monday: 8:00 AM – 5:00 PM","Tuesday: 8:00 AM – 5:00 PM","Wednesday: 8:00 AM – 5:00 PM","Thursday: 8:00 AM – 5:00 PM","Friday: 8:00 AM – 5:00 PM","Saturday: Closed","Sunday: Closed"]}',
        hoursSummary: 'Mon-Fri 8:00 AM - 5:00 PM, Sat-Sun Closed',
        mondayOpen: '0800',
        mondayClose: '1700',
        tuesdayOpen: '0800',
        tuesdayClose: '1700',
        wednesdayOpen: '0800',
        wednesdayClose: '1700',
        thursdayOpen: '0800',
        thursdayClose: '1700',
        fridayOpen: '0800',
        fridayClose: '1700',
        saturdayOpen: null,
        saturdayClose: null,
        sundayOpen: null,
        sundayClose: null,
        weekdayCloseTime: '17:00',
        closedSaturday: true,
        closedSunday: true,
        closesBefore6: true,
        afterHoursGap: true,
        score: {
          torqiFitScore: 60,
          leadGrade: 'B',
          dataConfidenceScore: 50,
          primaryBucket: 'After-Hours Revenue Leak',
          secondaryBuckets: 'No Text / Weak Digital Intake',
          salesHook: 'Your shop closes at 5:00 PM and doesn\'t have a website for customers to schedule repairs online. TorQi provides a dedicated 24/7 phone number and AI voice agent to capture after-hours bookings, so you don\'t miss out on business to competitors.',
          openingLine: 'Hi, I saw Apex Auto Electric is closed on weekends and closes at 5 PM. Since you don\'t have a website, customers can only reach you by calling during business hours. We help shops like yours capture bookings automatically via phone 24/7.',
          outreachPriority: 'Medium',
          scoreBreakdownJson: '{"closes_before_6":15,"closed_saturday":10,"closed_sunday":10,"rating_4_5_plus":10,"phone_available":5,"business_operational":5,"total":55}',
        },
        scan: {
          scanStatus: 'no_website',
          httpStatus: null,
          finalUrl: null,
          homepageTitle: null,
          pagesScanned: 0,
          appointmentPageFound: false,
          appointmentUrl: null,
          contactPageFound: false,
          contactUrl: null,
          bookingFlowStrength: 'Phone-first only',
          textCapability: 'Not Found',
          textEvidence: 'No website to scan.',
          chatWidgetFound: false,
          formFound: false,
          formType: null,
          detectedSoftware: null,
          softwareConfidence: null,
          softwareEvidence: null,
          evidenceUrl: null,
          rawSignalsJson: '{}',
        }
      }
    ];

    for (const lead of leadsData) {
      const dbLead = await prisma.lead.create({
        data: {
          campaignId: campaign1.id,
          placeId: Math.random().toString(36).substring(2, 15),
          businessName: lead.businessName,
          phoneRaw: lead.phoneRaw,
          phoneFormatted: lead.phoneFormatted,
          website: lead.website,
          address: lead.address,
          city: lead.city,
          state: lead.state,
          zip: lead.zip,
          latitude: lead.latitude,
          longitude: lead.longitude,
          googleMapsUrl: lead.googleMapsUrl,
          businessStatus: lead.businessStatus,
          rating: lead.rating,
          reviewCount: lead.reviewCount,
          primaryType: lead.primaryType,
          types: lead.types,
          hoursJson: lead.hoursJson,
          hoursSummary: lead.hoursSummary,
          mondayOpen: lead.mondayOpen,
          mondayClose: lead.mondayClose,
          tuesdayOpen: lead.tuesdayOpen,
          tuesdayClose: lead.tuesdayClose,
          wednesdayOpen: lead.wednesdayOpen,
          wednesdayClose: lead.wednesdayClose,
          thursdayOpen: lead.thursdayOpen,
          thursdayClose: lead.thursdayClose,
          fridayOpen: lead.fridayOpen,
          fridayClose: lead.fridayClose,
          saturdayOpen: lead.saturdayOpen,
          saturdayClose: lead.saturdayClose,
          sundayOpen: lead.sundayOpen,
          sundayClose: lead.sundayClose,
          weekdayCloseTime: lead.weekdayCloseTime,
          closedSaturday: lead.closedSaturday,
          closedSunday: lead.closedSunday,
          closesBefore6: lead.closesBefore6,
          afterHoursGap: lead.afterHoursGap,
        },
      });

      const scan = lead.scan as any;
      await prisma.websiteScan.create({
        data: {
          leadId: dbLead.id,
          scanStatus: scan.scanStatus,
          httpStatus: scan.httpStatus,
          finalUrl: scan.finalUrl,
          homepageTitle: scan.homepageTitle,
          pagesScanned: scan.pagesScanned,
          appointmentPageFound: scan.appointmentPageFound,
          appointmentUrl: scan.appointmentUrl,
          contactPageFound: scan.contactPageFound,
          contactUrl: scan.contactUrl,
          bookingFlowStrength: scan.bookingFlowStrength,
          textCapability: scan.textCapability,
          textEvidence: scan.textEvidence,
          chatWidgetFound: scan.chatWidgetFound,
          chatWidgetName: scan.chatWidgetName || null,
          formFound: scan.formFound,
          formType: scan.formType,
          detectedSoftware: scan.detectedSoftware,
          softwareConfidence: scan.softwareConfidence,
          softwareEvidence: scan.softwareEvidence,
          evidenceUrl: scan.evidenceUrl,
          rawSignalsJson: scan.rawSignalsJson,
        },
      });

      await prisma.leadScore.create({
        data: {
          leadId: dbLead.id,
          torqiFitScore: lead.score.torqiFitScore,
          leadGrade: lead.score.leadGrade,
          dataConfidenceScore: lead.score.dataConfidenceScore,
          primaryBucket: lead.score.primaryBucket,
          secondaryBuckets: lead.score.secondaryBuckets,
          salesHook: lead.score.salesHook,
          openingLine: lead.score.openingLine,
          outreachPriority: lead.score.outreachPriority,
          scoreBreakdownJson: lead.score.scoreBreakdownJson,
        },
      });
    }

    console.log('Mock leads seeded.');

    // 6. Create some logs
    await prisma.log.createMany({
      data: [
        {
          campaignId: campaign1.id,
          level: 'info',
          message: 'Campaign created and initialized.',
        },
        {
          campaignId: campaign1.id,
          level: 'info',
          message: 'Loaded 24 ZIP codes for Georgia.',
        },
        {
          campaignId: campaign1.id,
          level: 'info',
          message: 'Google Places Discovery completed. Found 152 place IDs.',
        },
        {
          campaignId: campaign1.id,
          level: 'info',
          message: 'Deduplicated places. 98 unique places remaining.',
        },
        {
          campaignId: campaign1.id,
          level: 'info',
          message: 'Enriched Place Details for 98 unique places.',
        },
        {
          campaignId: campaign1.id,
          level: 'info',
          message: 'Website scanning complete. Scanned 74 domains, 24 missing websites.',
        },
        {
          campaignId: campaign1.id,
          level: 'info',
          message: 'Scoring engine executed. 65 qualified leads found.',
        },
        {
          campaignId: campaign2.id,
          level: 'info',
          message: 'Campaign created and initialized.',
        },
        {
          campaignId: campaign2.id,
          level: 'info',
          message: 'Loaded 40 ZIP codes for Texas.',
        },
        {
          campaignId: campaign2.id,
          level: 'info',
          message: 'Google Places Discovery completed. Found 85 place IDs.',
        },
      ],
    });
    console.log('Mock logs created.');

    console.log('Database seeded successfully!');
  } catch (error) {
    console.error('Error seeding database:', error);
  } finally {
    await pool.end();
  }
}

main();
